### ISSUE TITLE
Crashes on first deploy

### ISSUE THREAD

**Issue by Dentrax** [clastix/capsule#745] opened 2023-03-31 06:17 UTC
# Bug description

I was trying to deploy Capsule with the [Getting Started](https://capsule.clastix.io/docs/general/getting-started) document. But when I issue the following YAML file installer, the pod suddenly crashes. But I observed no issues with Helm method.

# How to reproduce

```
kubectl apply -f https://raw.githubusercontent.com/clastix/capsule/master/config/install.yaml
```

# Expected behavior

# Logs

<details>
  <summary>Logs</summary>
  
  ```
  2023-03-29T10:38:11.675Z	ERROR	Could not wait for Cache to sync	{"controller": "tenant", "controllerGroup": "capsule.clastix.io", "controllerKind": "Tenant", "error": "failed to wait for tenant caches to sync: cache did not sync"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:215
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:241
sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/manager/runnable_group.go:219
2023-03-29T10:38:11.675Z	ERROR	controller-runtime.source	failed to get informer from cache	{"error": "Timeout: failed waiting for *v1.PersistentVolume Informer to sync"}
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/source/source.go:144
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:233
k8s.io/apimachinery/pkg/util/wait.poll
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:580
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:545
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/source/source.go:132
2023-03-29T10:38:11.675Z	INFO	Stopping and waiting for caches
2023-03-29T10:38:11.675Z	ERROR	error received after stop sequence was engaged	{"error": "failed to wait for tenant caches to sync: cache did not sync"}
sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).engageStopProcedure.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/manager/internal.go:541
2023-03-29T10:38:11.675Z	INFO	Stopping and waiting for webhooks
2023-03-29T10:38:11.675Z	INFO	Wait completed, proceeding to shutdown the manager
2023-03-29T10:38:11.675Z	ERROR	controller-runtime.source	failed to get informer from cache	{"error": "Timeout: failed waiting for *v1.NetworkPolicy Informer to sync"}
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/source/source.go:144
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:233
k8s.io/apimachinery/pkg/util/wait.poll
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:580
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:545
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/source/source.go:132
E0329 10:38:11.675422       1 leaderelection.go:330] error retrieving resource lock capsule-system/42c733ea.clastix.capsule.io: Get "[https://10.230.64.1:443/apis/coordination.k8s.io/v1/namespaces/capsule-system/leases/42c733ea.clastix.capsule.io](https://10.230.64.1/apis/coordination.k8s.io/v1/namespaces/capsule-system/leases/42c733ea.clastix.capsule.io)": context canceled
2023-03-29T10:38:11.675Z	ERROR	setup	problem running manager	{"error": "open /tmp/k8s-webhook-server/serving-certs/tls.crt: no such file or directory"}
main.main
	/workspace/main.go:330
runtime.main
	/usr/local/go/src/runtime/proc.go:250
   ```

</details>

# Additional context

- Capsule version: (`0.3.1`)
- Helm Chart version: (`-`)
- Kubernetes version: (`v1.23.7`)

**Comment by prometherion** [comment] 2023-03-31 08:58
Hey @Dentrax, I tried to replicate your issue but with no luck.

```
$: kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.25.3) 🖼
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a nice day! 👋

$: kubectl apply -f https://raw.githubusercontent.com/clastix/capsule/master/config/install.yaml
namespace/capsule-system created
customresourcedefinition.apiextensions.k8s.io/capsuleconfigurations.capsule.clastix.io created
customresourcedefinition.apiextensions.k8s.io/globaltenantresources.capsule.clastix.io created
customresourcedefinition.apiextensions.k8s.io/tenantresources.capsule.clastix.io created
customresourcedefinition.apiextensions.k8s.io/tenants.capsule.clastix.io created
clusterrolebinding.rbac.authorization.k8s.io/capsule-manager-rolebinding created
secret/capsule-ca created
secret/capsule-tls created
service/capsule-controller-manager-metrics-service created
service/capsule-webhook-service created
deployment.apps/capsule-controller-manager created
mutatingwebhookconfiguration.admissionregistration.k8s.io/capsule-mutating-webhook-configuration created
validatingwebhookconfiguration.admissionregistration.k8s.io/capsule-validating-webhook-configuration created
error: resource mapping not found for name: "capsule-default" namespace: "capsule-system" from "https://raw.githubusercontent.com/clastix/capsule/master/config/install.yaml": no matches for kind "CapsuleConfiguration" in version "capsule.clastix.io/v1beta2"
ensure CRDs are installed first

$: # this is a problem we're aware of, as explained here: https://github.com/clastix/capsule/issues/368#issuecomment-892735970

$: kubectl apply -f https://raw.githubusercontent.com/clastix/capsule/master/config/install.yaml
namespace/capsule-system unchanged
customresourcedefinition.apiextensions.k8s.io/capsuleconfigurations.capsule.clastix.io unchanged
customresourcedefinition.apiextensions.k8s.io/globaltenantresources.capsule.clastix.io unchanged
customresourcedefinition.apiextensions.k8s.io/tenantresources.capsule.clastix.io unchanged
customresourcedefinition.apiextensions.k8s.io/tenants.capsule.clastix.io unchanged
clusterrolebinding.rbac.authorization.k8s.io/capsule-manager-rolebinding unchanged
secret/capsule-ca unchanged
secret/capsule-tls unchanged
service/capsule-controller-manager-metrics-service unchanged
service/capsule-webhook-service unchanged
deployment.apps/capsule-controller-manager configured
capsuleconfiguration.capsule.clastix.io/capsule-default created
mutatingwebhookconfiguration.admissionregistration.k8s.io/capsule-mutating-webhook-configuration configured
validatingwebhookconfiguration.admissionregistration.k8s.io/capsule-validating-webhook-configuration configured

#: kubectl get pods -n capsule-system
NAME                                         READY   STATUS    RESTARTS   AGE
capsule-controller-manager-5479867f4-9xqjn   1/1     Running   0          14s
```

The capsule logs of that pod:
```
2023-03-31T08:55:52.491Z	INFO	setup	Capsule Version v0.3.1 07f479a
2023-03-31T08:55:52.491Z	INFO	setup	Build from: https://github.com/clastix/capsule
2023-03-31T08:55:52.491Z	INFO	setup	Build date: 2023-03-21T16:15:40
2023-03-31T08:55:52.491Z	INFO	setup	Go Version: go1.18.10
2023-03-31T08:55:52.491Z	INFO	setup	Go OS/Arch: linux/amd64
2023-03-31T08:55:52.690Z	INFO	controller-runtime.metrics	Metrics server is starting to listen	{"addr": ":8080"}
2023-03-31T08:55:52.703Z	INFO	controllers.TLS	Generating new TLS certificate
2023-03-31T08:56:18.713Z	INFO	controllers.TLS	Updating caBundle in webhooks and crd
2023-03-31T08:56:18.794Z	INFO	controllers.TLS	Updating capsule operator pods
2023-03-31T08:56:19.390Z	INFO	controller-runtime.builder	skip registering a mutating webhook, object does not implement admission.Defaulter or WithDefaulter wasn't called	{"GVK": "capsule.clastix.io/v1alpha1, Kind=Tenant"}
2023-03-31T08:56:19.391Z	INFO	controller-runtime.builder	skip registering a validating webhook, object does not implement admission.Validator or WithValidator wasn't called	{"GVK": "capsule.clastix.io/v1alpha1, Kind=Tenant"}
2023-03-31T08:56:19.391Z	INFO	controller-runtime.webhook	Registering webhook	{"path": "/convert"}
2023-03-31T08:56:19.391Z	INFO	controller-runtime.builder	Conversion webhook enabled	{"GVK": "capsule.clastix.io/v1alpha1, Kind=Tenant"}
2023-03-31T08:56:19.391Z	INFO	controller-runtime.builder	skip registering a mutating webhook, object does not implement admission.Defaulter or WithDefaulter wasn't called	{"GVK": "capsule.clastix.io/v1alpha1, Kind=CapsuleConfiguration"}
2023-03-31T08:56:19.391Z	INFO	controller-runtime.builder	skip registering a validating webhook, object does not implement admission.Validator or WithValidator wasn't called	{"GVK": "capsule.clastix.io/v1alpha1, Kind=CapsuleConfiguration"}
2023-03-31T08:56:19.391Z	INFO	controller-runtime.builder	Conversion webhook enabled	{"GVK": "capsule.clastix.io/v1alpha1, Kind=CapsuleConfiguration"}
2023-03-31T08:56:19.391Z	INFO	controller-runtime.builder	skip registering a mutating webhook, object does not implement admission.Defaulter or WithDefaulter wasn't called	{"GVK": "capsule.clastix.io/v1beta1, Kind=Tenant"}
2023-03-31T08:56:19.391Z	INFO	controller-runtime.builder	skip registering a validating webhook, object does not implement admission.Validator or WithValidator wasn't called	{"GVK": "capsule.clastix.io/v1beta1, Kind=Tenant"}
2023-03-31T08:56:19.391Z	INFO	controller-runtime.builder	Conversion webhook enabled	{"GVK": "capsule.clastix.io/v1beta1, Kind=Tenant"}
2023-03-31T08:56:19.399Z	INFO	setup	skipping setup of Indexer ingress.HostnamePath for object *v1beta1.Ingress	{"error": "no matches for kind \"Ingress\" in version \"extensions/v1beta1\""}
I0331 08:56:20.493250       1 request.go:601] Waited for 1.003674857s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/certificates.k8s.io/v1?timeout=32s
2023-03-31T08:56:20.797Z	INFO	setup	skipping setup of Indexer ingress.HostnamePath for object *v1beta1.Ingress	{"error": "no matches for kind \"Ingress\" in version \"networking.k8s.io/v1beta1\""}
2023-03-31T08:56:20.799Z	INFO	controller-runtime.webhook	Registering webhook	{"path": "/pods"}
2023-03-31T08:56:20.799Z	INFO	controller-runtime.webhook	Registering webhook	{"path": "/namespaces"}
2023-03-31T08:56:20.799Z	INFO	controller-runtime.webhook	Registering webhook	{"path": "/ingresses"}
2023-03-31T08:56:20.800Z	INFO	controller-runtime.webhook	Registering webhook	{"path": "/persistentvolumeclaims"}
2023-03-31T08:56:20.800Z	INFO	controller-runtime.webhook	Registering webhook	{"path": "/services"}
2023-03-31T08:56:20.800Z	INFO	controller-runtime.webhook	Registering webhook	{"path": "/tenantresource-objects"}
2023-03-31T08:56:20.800Z	INFO	controller-runtime.webhook	Registering webhook	{"path": "/networkpolicies"}
2023-03-31T08:56:20.800Z	INFO	controller-runtime.webhook	Registering webhook	{"path": "/tenants"}
2023-03-31T08:56:20.800Z	INFO	controller-runtime.webhook	Registering webhook	{"path": "/namespace-owner-reference"}
2023-03-31T08:56:20.800Z	INFO	controller-runtime.webhook	Registering webhook	{"path": "/cordoning"}
2023-03-31T08:56:20.801Z	INFO	controller-runtime.webhook	Registering webhook	{"path": "/nodes"}
2023-03-31T08:56:20.801Z	INFO	controller-runtime.webhook	Registering webhook	{"path": "/defaults"}
2023-03-31T08:56:20.801Z	INFO	setup	starting manager
2023-03-31T08:56:20.801Z	INFO	controller-runtime.webhook.webhooks	Starting webhook server
2023-03-31T08:56:20.801Z	INFO	controller-runtime.certwatcher	Updated current TLS certificate
2023-03-31T08:56:20.802Z	INFO	controller-runtime.webhook	Serving webhook server	{"host": "", "port": 9443}
2023-03-31T08:56:20.802Z	INFO	Starting server	{"path": "/metrics", "kind": "metrics", "addr": "[::]:8080"}
2023-03-31T08:56:20.802Z	INFO	Starting server	{"kind": "health probe", "addr": "[::]:10080"}
2023-03-31T08:56:20.812Z	INFO	controller-runtime.certwatcher	Starting certificate watcher
I0331 08:56:20.914025       1 leaderelection.go:248] attempting to acquire leader lease capsule-system/42c733ea.clastix.capsule.io...
I0331 08:56:20.922215       1 leaderelection.go:258] successfully acquired lease capsule-system/42c733ea.clastix.capsule.io
2023-03-31T08:56:20.922Z	INFO	controllers.Rbac	setting up ClusterRoles	{"ClusterRole": "capsule-namespace-provisioner"}
2023-03-31T08:56:20.922Z	INFO	Starting EventSource	{"controller": "secret", "controllerGroup": "", "controllerKind": "Secret", "source": "kind source: *v1.Secret"}
2023-03-31T08:56:20.922Z	INFO	Starting EventSource	{"controller": "tenant", "controllerGroup": "capsule.clastix.io", "controllerKind": "Tenant", "source": "kind source: *v1beta2.Tenant"}
2023-03-31T08:56:20.922Z	INFO	Starting EventSource	{"controller": "tenant", "controllerGroup": "capsule.clastix.io", "controllerKind": "Tenant", "source": "kind source: *v1.Namespace"}
2023-03-31T08:56:20.922Z	INFO	Starting EventSource	{"controller": "clusterrolebinding", "controllerGroup": "rbac.authorization.k8s.io", "controllerKind": "ClusterRoleBinding", "source": "kind source: *v1.ClusterRoleBinding"}
2023-03-31T08:56:20.922Z	INFO	Starting EventSource	{"controller": "tenant", "controllerGroup": "capsule.clastix.io", "controllerKind": "Tenant", "source": "kind source: *v1.NetworkPolicy"}
2023-03-31T08:56:20.922Z	INFO	Starting EventSource	{"controller": "tenant", "controllerGroup": "capsule.clastix.io", "controllerKind": "Tenant", "source": "kind source: *v1.LimitRange"}
2023-03-31T08:56:20.922Z	INFO	Starting EventSource	{"controller": "secret", "controllerGroup": "", "controllerKind": "Secret", "source": "&{{%!s(*v1.ValidatingWebhookConfiguration=&{{ } {      0 {{0 0 <nil>}} <nil> <nil> map[] map[] [] []  []} []}) %!s(*cache.informerCache=&{0xc00073c8e0}) %!s(chan error=<nil>) %!s(func()=<nil>)}}"}
2023-03-31T08:56:20.922Z	INFO	Starting EventSource	{"controller": "tenant", "controllerGroup": "capsule.clastix.io", "controllerKind": "Tenant", "source": "kind source: *v1.ResourceQuota"}
2023-03-31T08:56:20.922Z	INFO	Starting EventSource	{"controller": "tenant", "controllerGroup": "capsule.clastix.io", "controllerKind": "Tenant", "source": "kind source: *v1.RoleBinding"}
2023-03-31T08:56:20.922Z	INFO	Starting EventSource	{"controller": "clusterrolebinding", "controllerGroup": "rbac.authorization.k8s.io", "controllerKind": "ClusterRoleBinding", "source": "&{{%!s(*v1beta2.CapsuleConfiguration=&{{ } {      0 {{0 0 <nil>}} <nil> <nil> map[] map[] [] []  []} {[] false  {  } <nil> false}}) %!s(*cache.informerCache=&{0xc00073c8e0}) %!s(chan error=<nil>) %!s(func()=<nil>)}}"}
2023-03-31T08:56:20.922Z	INFO	Starting EventSource	{"controller": "secret", "controllerGroup": "", "controllerKind": "Secret", "source": "&{{%!s(*v1.MutatingWebhookConfiguration=&{{ } {      0 {{0 0 <nil>}} <nil> <nil> map[] map[] [] []  []} []}) %!s(*cache.informerCache=&{0xc00073c8e0}) %!s(chan error=<nil>) %!s(func()=<nil>)}}"}
2023-03-31T08:56:20.922Z	INFO	Starting Controller	{"controller": "clusterrolebinding", "controllerGroup": "rbac.authorization.k8s.io", "controllerKind": "ClusterRoleBinding"}
2023-03-31T08:56:20.922Z	INFO	Starting EventSource	{"controller": "endpoints", "controllerGroup": "", "controllerKind": "Endpoints", "source": "kind source: *v1.Endpoints"}
2023-03-31T08:56:20.922Z	INFO	Starting EventSource	{"controller": "clusterrole", "controllerGroup": "rbac.authorization.k8s.io", "controllerKind": "ClusterRole", "source": "kind source: *v1.ClusterRole"}
2023-03-31T08:56:20.922Z	INFO	Starting EventSource	{"controller": "secret", "controllerGroup": "", "controllerKind": "Secret", "source": "&{{%!s(*v1.CustomResourceDefinition=&{{ } {      0 {{0 0 <nil>}} <nil> <nil> map[] map[] [] []  []} { {  []   []}  [] <nil> false} {[] {  []   []} []}}) %!s(*cache.informerCache=&{0xc00073c8e0}) %!s(chan error=<nil>) %!s(func()=<nil>)}}"}
2023-03-31T08:56:20.922Z	INFO	Starting Controller	{"controller": "endpoints", "controllerGroup": "", "controllerKind": "Endpoints"}
2023-03-31T08:56:20.922Z	DEBUG	events	Normal	{"object": {"kind":"Lease","namespace":"capsule-system","name":"42c733ea.clastix.capsule.io","uid":"971af047-0394-430c-a431-cd94a8c4b0d5","apiVersion":"coordination.k8s.io/v1","resourceVersion":"930"}, "reason": "LeaderElection", "message": "capsule-controller-manager-5479867f4-9xqjn_93c6b52c-fecf-4728-b353-f3fe9fa44479 became leader"}
2023-03-31T08:56:20.922Z	INFO	Starting Controller	{"controller": "clusterrole", "controllerGroup": "rbac.authorization.k8s.io", "controllerKind": "ClusterRole"}
2023-03-31T08:56:20.922Z	INFO	Starting Controller	{"controller": "tenant", "controllerGroup": "capsule.clastix.io", "controllerKind": "Tenant"}
2023-03-31T08:56:20.922Z	INFO	Starting Controller	{"controller": "secret", "controllerGroup": "", "controllerKind": "Secret"}
2023-03-31T08:56:20.922Z	INFO	Starting EventSource	{"controller": "service", "controllerGroup": "", "controllerKind": "Service", "source": "kind source: *v1.Service"}
2023-03-31T08:56:20.922Z	INFO	Starting Controller	{"controller": "service", "controllerGroup": "", "controllerKind": "Service"}
2023-03-31T08:56:20.922Z	INFO	Starting EventSource	{"controller": "persistentvolume", "controllerGroup": "", "controllerKind": "PersistentVolume", "source": "kind source: *v1.PersistentVolume"}
2023-03-31T08:56:20.922Z	INFO	Starting Controller	{"controller": "persistentvolume", "controllerGroup": "", "controllerKind": "PersistentVolume"}
2023-03-31T08:56:20.922Z	INFO	Starting EventSource	{"controller": "endpointslice", "controllerGroup": "discovery.k8s.io", "controllerKind": "EndpointSlice", "source": "kind source: *v1.EndpointSlice"}
2023-03-31T08:56:20.922Z	INFO	Starting Controller	{"controller": "endpointslice", "controllerGroup": "discovery.k8s.io", "controllerKind": "EndpointSlice"}
2023-03-31T08:56:20.923Z	INFO	Starting EventSource	{"controller": "globaltenantresource", "controllerGroup": "capsule.clastix.io", "controllerKind": "GlobalTenantResource", "source": "kind source: *v1beta2.GlobalTenantResource"}
2023-03-31T08:56:20.923Z	INFO	Starting EventSource	{"controller": "globaltenantresource", "controllerGroup": "capsule.clastix.io", "controllerKind": "GlobalTenantResource", "source": "kind source: *v1beta2.Tenant"}
2023-03-31T08:56:20.923Z	INFO	Starting EventSource	{"controller": "tenantresource", "controllerGroup": "capsule.clastix.io", "controllerKind": "TenantResource", "source": "kind source: *v1beta2.TenantResource"}
2023-03-31T08:56:20.923Z	INFO	Starting Controller	{"controller": "globaltenantresource", "controllerGroup": "capsule.clastix.io", "controllerKind": "GlobalTenantResource"}
2023-03-31T08:56:20.923Z	INFO	Starting Controller	{"controller": "tenantresource", "controllerGroup": "capsule.clastix.io", "controllerKind": "TenantResource"}
2023-03-31T08:56:20.923Z	INFO	Starting EventSource	{"controller": "capsuleconfiguration", "controllerGroup": "capsule.clastix.io", "controllerKind": "CapsuleConfiguration", "source": "kind source: *v1beta2.CapsuleConfiguration"}
2023-03-31T08:56:20.923Z	INFO	Starting Controller	{"controller": "capsuleconfiguration", "controllerGroup": "capsule.clastix.io", "controllerKind": "CapsuleConfiguration"}
2023-03-31T08:56:21.388Z	INFO	controllers.Rbac	setting up ClusterRoles	{"ClusterRole": "capsule-namespace-deleter"}
2023-03-31T08:56:21.392Z	INFO	controllers.Rbac	setting up ClusterRoleBindings
2023-03-31T08:56:21.689Z	INFO	Starting workers	{"controller": "persistentvolume", "controllerGroup": "", "controllerKind": "PersistentVolume", "worker count": 1}
2023-03-31T08:56:21.691Z	INFO	Starting workers	{"controller": "capsuleconfiguration", "controllerGroup": "capsule.clastix.io", "controllerKind": "CapsuleConfiguration", "worker count": 1}
2023-03-31T08:56:21.691Z	INFO	Starting workers	{"controller": "endpoints", "controllerGroup": "", "controllerKind": "Endpoints", "worker count": 1}
2023-03-31T08:56:21.691Z	INFO	Starting workers	{"controller": "clusterrolebinding", "controllerGroup": "rbac.authorization.k8s.io", "controllerKind": "ClusterRoleBinding", "worker count": 1}
2023-03-31T08:56:21.691Z	INFO	Starting workers	{"controller": "clusterrole", "controllerGroup": "rbac.authorization.k8s.io", "controllerKind": "ClusterRole", "worker count": 1}
2023-03-31T08:56:21.691Z	INFO	controllers.CapsuleConfiguration	CapsuleConfiguration reconciliation started	{"request.name": "capsule-default"}
2023-03-31T08:56:21.691Z	INFO	controllers.CapsuleConfiguration	CapsuleConfiguration reconciliation finished	{"request.name": "capsule-default"}
2023-03-31T08:56:21.691Z	INFO	Starting workers	{"controller": "endpointslice", "controllerGroup": "discovery.k8s.io", "controllerKind": "EndpointSlice", "worker count": 1}
2023-03-31T08:56:21.691Z	INFO	Starting workers	{"controller": "service", "controllerGroup": "", "controllerKind": "Service", "worker count": 1}
2023-03-31T08:56:21.723Z	INFO	Starting workers	{"controller": "secret", "controllerGroup": "", "controllerKind": "Secret", "worker count": 1}
2023-03-31T08:56:21.723Z	INFO	Starting workers	{"controller": "tenantresource", "controllerGroup": "capsule.clastix.io", "controllerKind": "TenantResource", "worker count": 1}
2023-03-31T08:56:21.723Z	INFO	Starting workers	{"controller": "globaltenantresource", "controllerGroup": "capsule.clastix.io", "controllerKind": "GlobalTenantResource", "worker count": 1}
2023-03-31T08:56:21.727Z	INFO	controllers.TLS	Skipping TLS certificate generation as it is still valid	{"Request.Namespace": "capsule-system", "Request.Name": "capsule-tls"}
2023-03-31T08:56:21.727Z	INFO	controllers.TLS	Updating caBundle in webhooks and crd	{"Request.Namespace": "capsule-system", "Request.Name": "capsule-tls"}
2023-03-31T08:56:21.788Z	INFO	Starting workers	{"controller": "tenant", "controllerGroup": "capsule.clastix.io", "controllerKind": "Tenant", "worker count": 1}
2023-03-31T08:56:21.788Z	INFO	controllers.TLS	Updating capsule operator pods	{"Request.Namespace": "capsule-system", "Request.Name": "capsule-tls"}
2023-03-31T08:56:22.102Z	INFO	controllers.TLS	Reconciliation completed, processing back in 4247h59m45.897789759s	{"Request.Namespace": "capsule-system", "Request.Name": "capsule-tls"}
2023-03-31T08:56:22.104Z	INFO	controllers.TLS	Skipping TLS certificate generation as it is still valid	{"Request.Namespace": "capsule-system", "Request.Name": "capsule-tls"}
2023-03-31T08:56:22.104Z	INFO	controllers.TLS	Updating caBundle in webhooks and crd	{"Request.Namespace": "capsule-system", "Request.Name": "capsule-tls"}
2023-03-31T08:56:22.189Z	INFO	controllers.TLS	Updating capsule operator pods	{"Request.Namespace": "capsule-system", "Request.Name": "capsule-tls"}
2023-03-31T08:56:22.596Z	INFO	controllers.TLS	Reconciliation completed, processing back in 4247h59m45.40326556s	{"Request.Namespace": "capsule-system", "Request.Name": "capsule-tls"}
```

---

The problem your instance is facing is that the certificates for webhook configuration have not been generated, this could happen in environments with limited resources: try to increase the Deployment CPU consumption (since TLS generation requires more CPU cycles) and restart the pods, and let me know if this fixed your issue.

Anyway, I would suggest using the provided Helm Chart to manage Capsule since it allows fine-tuning and parameter settings.

**Comment by prometherion** [comment] 2023-04-13 10:24
> seems caused by resource dependencies and deployment sequence.
> should install crds first then use it

Duplicate of https://github.com/clastix/capsule/issues/368#issuecomment-892735970

**Closed** 2023-07-14 10:22 UTC
Labels: bug, duplicate, blocked-needs-validation
