### ISSUE TITLE
unable to setup indexers","error":"no matches for kind \"Tenant\" in version \"capsule.clastix.io/v1beta1\"","stacktrace":"main.main\n\t/workspace/main.go:228\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225

### ISSUE THREAD

**Issue by titansmc** [clastix/capsule#476] opened 2021-11-24 10:37 UTC
It doesn't look like I can access Clastix slack workspace, as announced here.

# Bug description

Controller manager doesn't want to start due to liveness probe failing

# How to reproduce

Brand new helm installation following the instructions (after `helm uninstall....` of an old capsule version)

# Expected behavior

to just deploy fine

# Logs

```
  Normal   Scheduled  31m                  default-scheduler  Successfully assigned capsule-system/capsule-controller-manager-7f778445cf-ppwcd to ops-k1n03t.domain.de
  Normal   Pulling    31m                  kubelet            Pulling image "quay.io/clastix/capsule:v0.1.0"
  Normal   Pulled     30m                  kubelet            Successfully pulled image "quay.io/clastix/capsule:v0.1.0" in 5.966040477s
  Warning  Unhealthy  30m                  kubelet            Liveness probe failed: Get "http://10.133.103.75:10080/healthz": dial tcp 10.133.103.75:10080: connect: connection refused
  Normal   Killing    30m                  kubelet            Container manager failed liveness probe, will be restarted
  Normal   Created    30m (x4 over 30m)    kubelet            Created container manager
  Normal   Pulled     30m (x3 over 30m)    kubelet            Container image "quay.io/clastix/capsule:v0.1.0" already present on machine
  Normal   Started    30m (x4 over 30m)    kubelet            Started container manager
  Warning  Unhealthy  30m (x4 over 30m)    kubelet            Readiness probe failed: Get "http://10.133.103.75:10080/readyz": dial tcp 10.133.103.75:10080: connect: connection refused
  Warning  Unhealthy  30m (x3 over 30m)    kubelet            Liveness probe failed: Get "http://10.133.103.75:10080/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  BackOff    56s (x138 over 30m)  kubelet            Back-off restarting failed container
```

# Additional context

- Capsule version: 0.1.0
- Helm Chart version: capsule-0.1.3	0.1.0 
- Kubernetes version: 
```
[root@ops-k1m01t ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:40:09Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:32:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by prometherion** [comment] 2021-11-24 10:54
Hi @titansmc, please, reach out to me using any social ([Twitter](https://twitter.com/tranchitellad) or [LinkedIn](https://www.linkedin.com/in/dariotranchitella)) so we can give access to our Slack workspace!

I think this could be a duplicate of #408, or at least related: the `helm uninstall` doesn't clean up the Custom Resource Definitions, and that's good since that would mean you're going to delete all the Tenant and with that all the Namespaces attached to it.

However, when performing a new installation of Capsule, since the CRDs are already there, these are not going to be updated: this process must be performed manually due to some design decision put in place by Helm.

This discussion occurred [here](https://github.com/clastix/capsule/issues/438#issuecomment-929169090) and with #408 we're planning to document the migration process. If it's ok for you, I would close this and eventually suggest you follow the new issue which will lead to a new PR with all the detailed steps for this topic.

**Comment by titansmc** [comment] 2021-11-24 11:27
you are right. For now I have just manually deleted the CRD and start over, I just need to keep going , in order to test the product

**Closed** 2021-11-24 11:38 UTC
Labels: documentation, duplicate
